import calendar

MONTH_ORDER = [
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
    "Jan",
    "Feb",
    "Mar",
]
DAYS_IN_MONTH = {
    "Apr": 30,
    "May": 31,
    "Jun": 30,
    "Jul": 31,
    "Aug": 31,
    "Sep": 30,
    "Oct": 31,
    "Nov": 30,
    "Dec": 31,
    "Jan": 31,
    "Feb": 28,
    "Mar": 31,
}


def safe_float(val):
    if val is None or val == "" or val == " ":
        return 0.0
    try:
        return float(val)
    except (ValueError, TypeError):
        return 0.0


def safe_divide(n, d):
    return n / d if d != 0 else 0.0


def _q(conn, sql, params=()):
    row = conn.execute(sql, params).fetchone()
    return safe_float(row[0]) if row else 0.0


def calculate_kpis(conn, fy_suffix):
    parts = fy_suffix.split("_")
    prev_fy = None
    if len(parts) == 2 and parts[0].isdigit() and parts[1].isdigit():
        prev_fy = f"{int(parts[0]) - 1:02d}_{int(parts[1]) - 1:02d}"

    table_name = f"kpis_{fy_suffix}"
    conn.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {table_name} (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kpi_name TEXT NOT NULL,
            month TEXT NOT NULL,
            value REAL,
            UNIQUE(kpi_name, month)
        )
    """
    )
    conn.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = '{table_name}'
                  AND column_name = 'id'
                  AND is_identity = 'NO'
                  AND column_default IS NULL
            ) THEN
                ALTER TABLE {table_name}
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END $$;
    """
    )
    conn.execute(f"DELETE FROM {table_name}")

    print(f"\n[KPI CALCULATION] Calculating for FY {fy_suffix}...")

    # Get distinct months in fiscal year order (PostgreSQL-compatible subquery)
    months = [
        row[0]
        for row in conn.execute(
            f"""
        SELECT month FROM (
            SELECT DISTINCT month,
                CASE month
                    WHEN 'Apr' THEN 1 WHEN 'May' THEN 2 WHEN 'Jun' THEN 3
                    WHEN 'Jul' THEN 4 WHEN 'Aug' THEN 5 WHEN 'Sep' THEN 6
                    WHEN 'Oct' THEN 7 WHEN 'Nov' THEN 8 WHEN 'Dec' THEN 9
                    WHEN 'Jan' THEN 10 WHEN 'Feb' THEN 11 WHEN 'Mar' THEN 12
                END AS sort_key
            FROM mty_{fy_suffix}
        ) t ORDER BY sort_key
    """
        ).fetchall()
    ]

    records = []

    # FY-aggregate accumulators (weighted numerator/denominator sums)
    fy_acc = {
        "gross_profit": 0.0, "ebitda": 0.0, "net_profit": 0.0, "total_sales": 0.0,
        "dio_num": 0.0, "cogs_total": 0.0,
        "dso_num": 0.0, "dpo_num": 0.0,
        "current_assets": 0.0, "current_liab": 0.0,
        "quick_num": 0.0,
        "debt_cov_den": 0.0, "int_cov_den": 0.0,
        "last_loans_liability": 0.0, "last_capital_account": 0.0,
        "last_cash": 0.0, "last_bank": 0.0,
    }

    for i, month in enumerate(months):
        print(f"  Processing {month}...")
        prev_month = months[i - 1] if i > 0 else None
        days = DAYS_IN_MONTH.get(month, 30)

        # ====== VALUES FROM MTY ======
        total_sales = _q(
            conn,
            f"SELECT value FROM mty_{fy_suffix} WHERE month=%s AND line_item='TOTAL SALES->'",
            (month,),
        )
        var_yarn = _q(
            conn,
            f"SELECT value FROM mty_{fy_suffix} WHERE month=%s AND line_item='Variable-Yarn Cost'",
            (month,),
        )
        gross_profit = _q(
            conn,
            f"SELECT value FROM mty_{fy_suffix} WHERE month=%s AND line_item='Gross Profit'",
            (month,),
        )
        ebitda = _q(
            conn,
            f"SELECT value FROM mty_{fy_suffix} WHERE month=%s AND line_item='EBITDA'",
            (month,),
        )
        net_profit = _q(
            conn,
            f"SELECT value FROM mty_{fy_suffix} WHERE month=%s AND line_item='Nett Profit'",
            (month,),
        )
        cogs_monofil = _q(
            conn,
            f"SELECT value FROM mty_{fy_suffix} WHERE month=%s AND line_item='COGS Monofil'",
            (month,),
        )
        cogs_misc = _q(
            conn,
            f"SELECT value FROM mty_{fy_suffix} WHERE month=%s AND line_item='COGS Misc Trading'",
            (month,),
        )

        # 1. Revenue Growth
        if month == "Apr" and prev_fy:
            try:
                prev_total_sales = _q(
                    conn,
                    f"SELECT value FROM mty_{prev_fy} WHERE month=%s AND line_item='TOTAL SALES->'",
                    ("Mar",),
                )
            except Exception:
                prev_total_sales = 0.0
        else:
            prev_total_sales = _q(
                conn,
                f"SELECT value FROM mty_{fy_suffix} WHERE month=%s AND line_item='TOTAL SALES->'",
                (prev_month,),
            )
        rev_growth = round(
            safe_divide((total_sales - prev_total_sales), prev_total_sales) * 100.0,
            2,
        )

        # 2. Gross Margin
        gross_margin = round(safe_divide(gross_profit, total_sales) * 100.0, 2)

        # 3. EBITDA Margin
        ebitda_margin = round(safe_divide(ebitda, total_sales) * 100.0, 2)

        # 4. Net Margin
        net_margin = round(safe_divide(net_profit, total_sales) * 100.0, 2)

        # ====== STOCK VALUATION ======
        stock_val_query = f"""
            SELECT SUM(value) FROM stock_valuation_{fy_suffix} 
            WHERE month=%s AND material NOT IN ('Seconds', 'Packing Materials', 'Work in Progress')
        """
        sv_curr = _q(conn, stock_val_query, (month,))

        if month == "Apr":
            sv_prev = _q(
                conn,
                f"""
                SELECT SUM(value) FROM stock_valuation_{fy_suffix} 
                WHERE month='Op Stock' AND material NOT IN ('Seconds', 'Packing Materials', 'Work in Progress')
            """,
            )
        else:
            sv_prev = _q(conn, stock_val_query, (prev_month,))

        cogs_total = cogs_monofil + cogs_misc
        avg_stock = (sv_curr + sv_prev) / 2

        # 6. DIO (Days Inventory Outstanding)
        dio = round(safe_divide(avg_stock, cogs_total) * days, 2)

        # ====== BALANCE SHEET ======
        sundry_debtors = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND line_item='Sundry Debtors'",
            (month,),
        )
        sundry_creditors = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND line_item='Sundry Creditors'",
            (month,),
        )

        current_assets = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND category='Current Assets'",
            (month,),
        )
        current_liab = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND category='Current Liabilities'",
            (month,),
        )

        closing_stock = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND line_item='Closing Stock'",
            (month,),
        )
        loans_advances_str = "Loans & Advances"
        loans_advances = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND line_item=%s",
            (month, loans_advances_str),
        )

        loans_liability = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND category='Loans (Liability)'",
            (month,),
        )
        capital_account = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND category='Capital Account'",
            (month,),
        )

        cash_in_hand = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND line_item='Cash-in-hand'",
            (month,),
        )
        bank_accounts = _q(
            conn,
            f"SELECT SUM(value) FROM balance_sheet_{fy_suffix} WHERE month=%s AND line_item='Bank Accounts'",
            (month,),
        )

        # ====== DIRECT EXPENSES OUTPUT ======
        working_cap_arr = [
            "Working Capital-Bank Charges",
            "Working Capital-LC",
            "Working Capital-OCC",
            "Finance Cost-Int On Term Loan",
            "Finance Cost-Int On Deposits",
        ]
        working_cap_query = f"SELECT SUM(value) FROM direct_expenses_output_{fy_suffix} WHERE month=%s AND particulars IN ({','.join('%s' for _ in working_cap_arr)})"
        finance_costs = _q(conn, working_cap_query, (month, *working_cap_arr))

        # 7. DSO (Days Sales Outstanding)
        dso = round(safe_divide(sundry_debtors, total_sales) * days, 2)

        # 8. DPO (Days Payable Outstanding)
        dpo = round(safe_divide(sundry_creditors, total_sales) * days, 2)

        # 5. CCC (Cash Conversion Cycle)
        ccc = round(dio + dso - dpo, 2)

        # 9. Current Ratio
        current_ratio = round(safe_divide(current_assets, current_liab), 2)

        # 10. Quick Ratio
        quick_ratio = round(
            safe_divide(
                (current_assets - closing_stock - loans_advances), current_liab
            ),
            2,
        )

        # 11. Debt Equity
        debt_equity = round(safe_divide(loans_liability, capital_account), 2)

        # 12. Debt Coverage
        debt_coverage = round(safe_divide(ebitda, (loans_liability + finance_costs)), 2)

        # 13. Interest Coverage (EBITDA/Interest)
        interest_coverage = round(safe_divide(ebitda, finance_costs), 2)

        # 14. EV (Enterprise Value)
        ev = round(capital_account + loans_liability - cash_in_hand - bank_accounts, 2)

        kpis = {
            "Revenue growth": rev_growth,
            "Gross margin": gross_margin,
            "EBITDA": ebitda_margin,
            "Net Margin": net_margin,
            "CCC (cash conversion cycle)": ccc,
            "DIO (Days Inventory Outstanding)": dio,
            "DSO (Days sales Outstanding)": dso,
            "DPO (Days Payable Outstanding)": dpo,
            "Current Ratio": current_ratio,
            "Quick Ratio": quick_ratio,
            "Debt Equity": debt_equity,
            "Debt Coverage": debt_coverage,
            "Interest Coverage": interest_coverage,
            "EV (Enterprise Value)": ev,
        }

        # Accumulate FY totals
        fy_acc["gross_profit"] += gross_profit
        fy_acc["ebitda"] += ebitda
        fy_acc["net_profit"] += net_profit
        fy_acc["total_sales"] += total_sales
        fy_acc["dio_num"] += avg_stock * days
        fy_acc["cogs_total"] += cogs_total
        fy_acc["dso_num"] += sundry_debtors * days
        fy_acc["dpo_num"] += sundry_creditors * days
        fy_acc["current_assets"] += current_assets
        fy_acc["current_liab"] += current_liab
        fy_acc["quick_num"] += (current_assets - closing_stock - loans_advances)
        fy_acc["debt_cov_den"] += loans_liability + finance_costs
        fy_acc["int_cov_den"] += finance_costs
        fy_acc["last_loans_liability"] = loans_liability
        fy_acc["last_capital_account"] = capital_account
        fy_acc["last_cash"] = cash_in_hand
        fy_acc["last_bank"] = bank_accounts

        for k, v in kpis.items():
            records.append((k, month, v))

    # ── FY Aggregate rows (month = 'FY') ─────────────────────────────────────
    fy_gross_margin    = round(safe_divide(fy_acc["gross_profit"], fy_acc["total_sales"]) * 100.0, 2)
    fy_ebitda_margin   = round(safe_divide(fy_acc["ebitda"],       fy_acc["total_sales"]) * 100.0, 2)
    fy_net_margin      = round(safe_divide(fy_acc["net_profit"],   fy_acc["total_sales"]) * 100.0, 2)
    fy_dio             = round(safe_divide(fy_acc["dio_num"],      fy_acc["cogs_total"]),  2)
    fy_dso             = round(safe_divide(fy_acc["dso_num"],      fy_acc["total_sales"]), 2)
    fy_dpo             = round(safe_divide(fy_acc["dpo_num"],      fy_acc["total_sales"]), 2)
    fy_ccc             = round(fy_dio + fy_dso - fy_dpo, 2)
    fy_current_ratio   = round(safe_divide(fy_acc["current_assets"], fy_acc["current_liab"]),   2)
    fy_quick_ratio     = round(safe_divide(fy_acc["quick_num"],      fy_acc["current_liab"]),   2)
    fy_debt_equity     = round(safe_divide(fy_acc["last_loans_liability"], fy_acc["last_capital_account"]), 2)
    fy_debt_coverage   = round(safe_divide(fy_acc["ebitda"], fy_acc["debt_cov_den"]), 2)
    fy_interest_cov    = round(safe_divide(fy_acc["ebitda"], fy_acc["int_cov_den"]),  2)
    fy_ev              = round(
        fy_acc["last_capital_account"] + fy_acc["last_loans_liability"]
        - fy_acc["last_cash"] - fy_acc["last_bank"], 2
    )

    fy_kpis = {
        "Revenue growth":                   None,   # MoM % — not aggregable as FY sum
        "Gross margin":                     fy_gross_margin,
        "EBITDA":                           fy_ebitda_margin,
        "Net Margin":                       fy_net_margin,
        "CCC (cash conversion cycle)":      fy_ccc,
        "DIO (Days Inventory Outstanding)": fy_dio,
        "DSO (Days sales Outstanding)":     fy_dso,
        "DPO (Days Payable Outstanding)":   fy_dpo,
        "Current Ratio":                    fy_current_ratio,
        "Quick Ratio":                      fy_quick_ratio,
        "Debt Equity":                      fy_debt_equity,
        "Debt Coverage":                    fy_debt_coverage,
        "Interest Coverage":                fy_interest_cov,
        "EV (Enterprise Value)":            fy_ev,
    }
    for k, v in fy_kpis.items():
        records.append((k, "FY", v))

    conn.executemany(
        f"""
        INSERT INTO {table_name} (kpi_name, month, value) VALUES (%s, %s, %s)
    """,
        records,
    )
    conn.commit()
    print(f"  ✓ Inserted {len(records)} KPI records.")

    return len(records)


if __name__ == "__main__":
    from sheets.db import get_connection

    conn = get_connection()
    calculate_kpis(conn, "25_26")
    conn.close()
