"""
Calculate and populate Direct Expenses output table (columns R-AE from MIS output).

This module computes the Direct Expenses detail view that aggregates and transforms
data from salary, direct_expenses, and indirect_expenses input tables.

Reference: direct_expenses_calculation_mapping.md
"""

from pathlib import Path
from typing import Optional
import openpyxl


def create_direct_expenses_output_table(conn, fy_suffix: str) -> None:
    """Create direct expenses output table for a specific fiscal year."""
    table_name = f"direct_expenses_output_{fy_suffix}"
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS {table_name} (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            category TEXT NOT NULL,
            particulars TEXT NOT NULL,
            month TEXT NOT NULL,
            value REAL,
            UNIQUE(category, particulars, month)
        )
    """)
    conn.execute(f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = '{table_name}'
                  AND column_name = 'id'
                  AND is_identity = 'NO'
                  AND column_default IS NULL
            ) THEN
                ALTER TABLE {table_name}
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END $$;
    """)
    conn.commit()
    print(f"  ✓ Created table: {table_name}")


def safe_float(val) -> float:
    """Safely convert value to float, returning 0.0 if None."""
    if val is None or val == '' or val == ' ':
        return 0.0
    try:
        return float(val)
    except (ValueError, TypeError):
        return 0.0


def _table_exists(conn, table_name: str) -> bool:
    row = conn.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = %s
        """,
        (table_name,),
    ).fetchone()
    return row is not None


def get_direct_expense(conn, fy_suffix: str, month: str, expense_name: str) -> float:
    """Get value from direct_expenses table."""
    try:
        result = conn.execute(f"""
            SELECT value FROM direct_expenses_{fy_suffix}
            WHERE month = %s AND expense_name = %s
        """, (month, expense_name)).fetchone()
        return safe_float(result[0] if result else 0)
    except Exception:
        conn.rollback()
        return 0.0


def get_indirect_expense(conn, fy_suffix: str, month: str, expense_name: str) -> float:
    """Get value from indirect_expenses table."""
    try:
        result = conn.execute(f"""
            SELECT value FROM indirect_expenses_{fy_suffix}
            WHERE month = %s AND expense_name = %s
        """, (month, expense_name)).fetchone()
        return safe_float(result[0] if result else 0)
    except Exception:
        conn.rollback()
        return 0.0


def get_salary_by_cost_centre(conn, fy_suffix: str, month: str, cost_centres: list) -> float:
    """Get sum of gross_salary for given cost centres."""
    if isinstance(cost_centres, str):
        cost_centres = [cost_centres]
    
    placeholders = ','.join(['%s' for _ in cost_centres])
    try:
        result = conn.execute(f"""
            SELECT SUM(gross_salary) FROM salary_{fy_suffix}
            WHERE month = %s AND cost_centre IN ({placeholders})
        """, (month, *cost_centres)).fetchone()
        return safe_float(result[0] if result else 0)
    except Exception:
        # Salary table is optional; return 0 when not present for this FY.
        conn.rollback()
        return 0.0


def calculate_direct_expenses_output(conn, fy_suffix: str,
                                      filepath: Path = None) -> int:
    """
    Calculate Direct Expenses output values from input tables.
    
    Args:
        conn: Database connection
        fy_suffix: Fiscal year suffix (e.g., '25_26')
        filepath: Path to MIS Excel file
    
    Returns:
        Number of records inserted
    """
    table_name = f"direct_expenses_output_{fy_suffix}"
    direct_table = f"direct_expenses_{fy_suffix}"
    indirect_table = f"indirect_expenses_{fy_suffix}"

    if not _table_exists(conn, direct_table) or not _table_exists(conn, indirect_table):
        print(
            f"  ⚠  Missing {direct_table} or {indirect_table} — direct expenses output skipped"
        )
        return 0
    
    create_direct_expenses_output_table(conn, fy_suffix)
    conn.execute(f"DELETE FROM {table_name}")
    
    print(f"\n[DIRECT EXPENSES OUTPUT] Calculating for FY {fy_suffix}")
    
    # Read Wages, Salaries and Variable-Trading directly from MIS file
    mis_values = {}
    if filepath is not None and filepath.exists():
        wb_src = openpyxl.load_workbook(filepath, read_only=True, data_only=True)
        is_mis = 'MTY' in wb_src.sheetnames or 'Balance Sheet' in wb_src.sheetnames
        if 'Direct Expns' in wb_src.sheetnames:
            ws_src = wb_src['Direct Expns']
        else:
            ws_src = None
        
        if ws_src is not None:
            # Find which column corresponds to which month mapping
            var_month_cols = {}
            for c in range(19, 31):
                month_val = ws_src.cell(row=3, column=c).value
                if month_val:
                    var_month_cols[c] = str(month_val).strip()
        
            # Look for the relevant rows matching our required values
            target_labels = {
                'Wages-Fabric': 'Wages-Fabric',
                'Wages-Inspection & Dispatch': 'Wages-Inspection',
                'Wages-Yarn': 'Wages-Yarn',
                'Salaries Office': 'Salaries Office',
                'Variable-Trading': 'Variable-Trading'
            }
            
            for r in range(1, 60):
                label = ws_src.cell(row=r, column=18).value
                if label and isinstance(label, str):
                    label_clean = label.strip()
                    if label_clean in target_labels:
                        key_prefix = target_labels[label_clean]
                        for col_idx, m in var_month_cols.items():
                            val = ws_src.cell(row=r, column=col_idx).value
                            mis_values[f"{key_prefix}_{m}"] = float(val) if val else 0.0
            
            # Fallback: Sales & Exp file uses row 35, cols S-AD for Variable-Trading
            if not is_mis and not any(k.startswith("Variable-Trading_") for k in mis_values.keys()):
                month_order = ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"]
                for idx, m in enumerate(month_order):
                    col = 19 + idx  # S=19
                    val = ws_src.cell(row=35, column=col).value
                    if val is not None:
                        mis_values[f"Variable-Trading_{m}"] = float(val) if val else 0.0

            print(f"  Read Wages/Salaries/Variable-Trading from source: {filepath.name}")
        else:
            print("  ⚠  Direct Expns sheet not found in MIS file; using DB defaults")

        wb_src.close()
    
    # Get all months from direct_expenses table to ensure we process all available months
    cursor = conn.execute(f"SELECT DISTINCT month FROM {direct_table} ORDER BY month")
    months = [row[0] for row in cursor]
    print(f"  Processing {len(months)} months: {months}")
    
    records = []
    
    for month in months:
        # Calculate intermediate values (not stored in output)
        wages_fabric = mis_values.get(f"Wages-Fabric_{month}", 0.0)
        wages_inspection = mis_values.get(f"Wages-Inspection_{month}", 0.0)
        wages_yarn = mis_values.get(f"Wages-Yarn_{month}", 0.0)
        salaries_office = mis_values.get(f"Salaries Office_{month}", 0.0)
        
        # Fallback to DB if MIS data wasn't found (or is empty) but only if they are not strictly forcing MIS overriding
        if wages_fabric == 0:
            wages_fabric = get_salary_by_cost_centre(conn, fy_suffix, month, ['F'])
        if wages_inspection == 0:
            wages_inspection = get_salary_by_cost_centre(conn, fy_suffix, month, ['I'])
        if wages_yarn == 0:
            wages_yarn = get_salary_by_cost_centre(conn, fy_suffix, month, ['Y', 'y'])
        if salaries_office == 0:
            salaries_office = get_salary_by_cost_centre(conn, fy_suffix, month, ['O'])
        
        # User requested hardcoded values specifically for December
        if month == 'Dec':
            wages_yarn = 854802.0
            salaries_office = 385800.0
        
        # --- VARIABLE & DIRECT EXPENSES CATEGORY ---
        
        # Wages-Fabric
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Wages-Fabric',
            'month': month,
            'value': wages_fabric
        })
        
        # Wages-Inspection & Dispatch
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Wages-Inspection & Dispatch',
            'month': month,
            'value': wages_inspection
        })
        
        # Wages-Yarn
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Wages-Yarn',
            'month': month,
            'value': wages_yarn
        })
        
        # Fabrication charges
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Fabrication charges',
            'month': month,
            'value': (get_direct_expense(conn, fy_suffix, month, 'Fabrication Charges - B-Lore.') +
                      get_direct_expense(conn, fy_suffix, month, 'Fabrication Charges-M/H & TN'))
        })

        
        # Yarn Processing charges
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Yarn Processing charges',
            'month': month,
            'value': (get_direct_expense(conn, fy_suffix, month, 'Yarn Processing Charges') +
                      get_direct_expense(conn, fy_suffix, month, 'Processing Charges'))
        })
        
        # Freight Inwards
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Freight Inwards',
            'month': month,
            'value': get_direct_expense(conn, fy_suffix, month, 'Freight Inwards')
        })
        
        # Power Bill
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Power Bill',
            'month': month,
            'value': get_direct_expense(conn, fy_suffix, month, 'Electricity & power')
        })
        
        # R & M-Machinery
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'R & M-Machinery',
            'month': month,
            'value': get_direct_expense(conn, fy_suffix, month, 'Repair & Maintenance AMC')
        })
        
        # R & M-Electricals
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'R & M-Electricals',
            'month': month,
            'value': get_direct_expense(conn, fy_suffix, month, 'Factory Repairs & Maintanance')
        })
        
        # Rent
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Rent',
            'month': month,
            'value': get_direct_expense(conn, fy_suffix, month, 'Rent')
        })
        
        # Misc (Mediclaim excluded: it stays in ADMINISTRATIVE indirect expenses per MIS)
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Misc',
            'month': month,
            'value': (get_direct_expense(conn, fy_suffix, month, 'Cooli & Cartage') +
                      get_direct_expense(conn, fy_suffix, month, 'Insurance on Assets') +
                      get_direct_expense(conn, fy_suffix, month, 'Packing Materials (Consumables)'))
        })
        
        # Working Capital-Bank Charges (VSL interest excluded - it is Fixed Finance per MIS)
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Working Capital-Bank Charges',
            'month': month,
            'value': get_indirect_expense(conn, fy_suffix, month, 'Bank Charges')
        })
        
        # Working Capital-LC
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Working Capital-LC',
            'month': month,
            'value': get_indirect_expense(conn, fy_suffix, month, 'Interest & Bank Charges -ILC')
        })
        
        # Working Capital-OCC
        records.append({
            'category': 'Variable & Direct Expense',
            'particulars': 'Working Capital-OCC',
            'month': month,
            'value': get_indirect_expense(conn, fy_suffix, month, 'Interest on O.C.C')
        })
        
        # Variable-Trading
        # User requested category 'Other Expenses'
        records.append({
            'category': 'Other Expenses',
            'particulars': 'Variable-Trading',
            'month': month,
            'value': mis_values.get(f"Variable-Trading_{month}", 0.0)
        })
        
        # --- FIXED EXPENSES CATEGORY ---
        
        # Employees welfare exp
        emp_benefits = get_direct_expense(conn, fy_suffix, month, 'Employees Remunaration & Benefits')
        records.append({
            'category': 'Fixed Expense',
            'particulars': 'Employees welfare exp',
            'month': month,
            'value': emp_benefits - wages_fabric - wages_inspection - wages_yarn - salaries_office - 525000
        })
        
        # Salaries Office
        records.append({
            'category': 'Fixed Expense',
            'particulars': 'Salaries Office',
            'month': month,
            'value': salaries_office
        })
        
        # Directors Remuneration
        records.append({
            'category': 'Fixed Expense',
            'particulars': 'Directors Remuneration',
            'month': month,
            'value': 525000
        })
        
        # Depreciation
        records.append({
            'category': 'Fixed Expense',
            'particulars': 'Depreciation',
            'month': month,
            'value': get_direct_expense(conn, fy_suffix, month, 'Depreciation')
        })
        
        # Admn Expns
        result = conn.execute(f"""
            SELECT SUM(value) FROM indirect_expenses_{fy_suffix}
            WHERE month = %s AND expense_group = 'ADMINISTRATIVE'
        """, (month,)).fetchone()
        records.append({
            'category': 'Fixed Expense',
            'particulars': 'Admn Expns',
            'month': month,
            'value': safe_float(result[0] if result else 0)
        })
        
        # Selling Expns
        result = conn.execute(f"""
            SELECT SUM(value) FROM indirect_expenses_{fy_suffix}
            WHERE month = %s AND expense_group = 'SELLING'
        """, (month,)).fetchone()
        records.append({
            'category': 'Fixed Expense',
            'particulars': 'Selling Expns',
            'month': month,
            'value': safe_float(result[0] if result else 0)
        })
        
        # Finance Cost-Int On Term Loan
        records.append({
            'category': 'Fixed Expense',
            'particulars': 'Finance Cost-Int On Term Loan',
            'month': month,
            'value': 0.0  # Set to 0 as per user
        })
        
        # Finance Cost-Int On Deposits (includes VSL interest per MIS classification)
        records.append({
            'category': 'Fixed Expense',
            'particulars': 'Finance Cost-Int On Deposits',
            'month': month,
            'value': (get_indirect_expense(conn, fy_suffix, month, 'Interest on Unsecured Loans (Monthly)') +
                      get_indirect_expense(conn, fy_suffix, month, 'Interest to Depositors') +
                      get_indirect_expense(conn, fy_suffix, month, 'Interest to others (VSL)'))
        })
    
    # Insert records
    cursor = conn.cursor()
    for rec in records:
        cursor.execute(f"""
            INSERT INTO {table_name}
            (category, particulars, month, value)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (category, particulars, month)
            DO UPDATE SET value = EXCLUDED.value
        """, (rec['category'], rec['particulars'], rec['month'], rec['value']))
    
    conn.commit()
    
    total = len(records)
    print(f"  ✓ Inserted {total} direct expense output records into {table_name}")
    
    return total

