"""
Ingest per-product purchase register from the annual Purchase Register Excel file.

Source file: "Purchase Register April25-Mar26.xlsx"
    Col 0: Date
    Col 1: Month  (e.g. 'Apr-25', 'May-25', ..., 'Mar-26')
    Col 2: Product Code  (integer)
    Col 3: Product Name
    Col 4: Category
    Col 5: QTY (Kg)
    Col 6: QTY (Meters)
    Col 7: Value  (purchase cost)

Only fabric/trading categories are included (goods bought for resale):
    PURCHASE_CATEGORIES = {'Monofil Fabric', 'Trading/Fabric'}

Rows with no Kg quantity are skipped.  Multiple rows per product are summed.

Target table: item_purchases_{fy}
    product_id           INT
    month                TEXT
    qty                  REAL   -- total purchased qty in kg
    purchase_rate_per_kg REAL   -- total value / total qty (cost per kg)

Existing rows for the given month are deleted before re-inserting (idempotent).
"""

from pathlib import Path
from collections import defaultdict

import openpyxl

from .db import get_connection

# Month label in Excel → three-letter abbreviation used everywhere else
_MONTH_LABEL_MAP = {
    "Apr-25": "Apr", "May-25": "May", "Jun-25": "Jun", "Jul-25": "Jul",
    "Aug-25": "Aug", "Sep-25": "Sep", "Oct-25": "Oct", "Nov-25": "Nov",
    "Dec-25": "Dec", "Jan-26": "Jan", "Feb-26": "Feb", "Mar-26": "Mar",
    # FY 26-27 labels if file is ever extended
    "Apr-26": "Apr", "May-26": "May", "Jun-26": "Jun", "Jul-26": "Jul",
    "Aug-26": "Aug", "Sep-26": "Sep", "Oct-26": "Oct", "Nov-26": "Nov",
    "Dec-26": "Dec", "Jan-27": "Jan", "Feb-27": "Feb", "Mar-27": "Mar",
}

# Only these categories represent goods purchased for resale
PURCHASE_CATEGORIES = {"Monofil Fabric", "Trading/Fabric"}


def _create_table(conn, fy: str) -> None:
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS item_purchases_{fy} (
            id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id           INTEGER NOT NULL,
            month                TEXT    NOT NULL,
            qty                  REAL,
            purchase_rate_per_kg REAL
        )
    """)
    conn.execute(f"""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_item_purchases_{fy}_pid_month
        ON item_purchases_{fy} (product_id, month)
    """)
    conn.commit()


def ingest_item_purchases(conn, filepath: Path, fy: str, month: str) -> None:
    """
    Read purchase register rows for *month* from *filepath* and upsert into
    item_purchases_{fy}.

    Reads ALL sheets whose first cell is 'Date' (covers PurchaseRegister and
    any month-specific overflow sheets like March26).

    Only products present in product_specification are kept — trading goods
    such as PP Woven Sacks and Weed Mat are excluded.

    Parameters
    ----------
    conn      : DB connection returned by get_connection()
    filepath  : Path to the Purchase Register Excel file
    fy        : FY suffix, e.g. '25_26'
    month     : Three-letter month abbreviation, e.g. 'Mar'
    """
    # Fetch allowed product_ids from product_specification (manufactured only)
    allowed_cur = conn.execute(
        "SELECT DISTINCT product_code FROM product_specification WHERE product_code IS NOT NULL"
    )
    allowed_ids = {row[0] for row in allowed_cur.fetchall()}

    wb = openpyxl.load_workbook(filepath, data_only=True, read_only=True)

    totals: dict[int, dict] = defaultdict(lambda: {"qty": 0.0, "value": 0.0})
    skipped_no_qty = 0

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        # Skip pivot/summary sheets — data sheets have 'Date' in A1
        first_row = next(ws.iter_rows(min_row=1, max_row=1, values_only=True), ())
        if not first_row or str(first_row[0] or "").strip() != "Date":
            continue

        for row in ws.iter_rows(min_row=2, values_only=True):
            row_month_label = row[1]
            if not row_month_label:
                continue
            row_month = _MONTH_LABEL_MAP.get(str(row_month_label).strip())
            if row_month != month:
                continue

            category = row[4]
            if not category or str(category).strip() not in PURCHASE_CATEGORIES:
                continue

            pid = row[2]
            if pid is None:
                continue
            try:
                pid = int(pid)
            except (ValueError, TypeError):
                continue

            qty_kg = row[5]
            value  = row[7]
            qty_f  = float(qty_kg or 0)
            if qty_f <= 0:
                skipped_no_qty += 1
                continue

            totals[pid]["qty"]   += qty_f
            totals[pid]["value"] += float(value or 0)

    wb.close()

    # Filter to manufactured products only
    before = len(totals)
    totals = {pid: d for pid, d in totals.items() if pid in allowed_ids}
    excluded = before - len(totals)

    print(
        f"  [{month}] Found {len(totals)} manufactured products in purchase register"
        + (f" ({excluded} trading/other excluded)" if excluded else "")
        + (f" ({skipped_no_qty} rows skipped — no Kg qty)" if skipped_no_qty else "")
    )

    _create_table(conn, fy)
    conn.execute(f"DELETE FROM item_purchases_{fy} WHERE month = %s", (month,))

    inserted = 0
    for pid, d in totals.items():
        qty  = d["qty"]
        rate = d["value"] / qty if qty else 0.0
        conn.execute(
            f"""INSERT INTO item_purchases_{fy} (product_id, month, qty, purchase_rate_per_kg)
                VALUES (%s, %s, %s, %s)""",
            (pid, month, qty, rate),
        )
        inserted += 1

    print(f"  [{month}] Inserted {inserted} rows into item_purchases_{fy}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 4:
        print("Usage: python -m sheets.ingest_item_purchases <filepath> <fy> <month[,month,...]>")
        print("  e.g. python -m sheets.ingest_item_purchases 'Purchase Register April25-Mar26.xlsx' 25_26 Apr,May,Jun")
        sys.exit(1)

    fp  = Path(sys.argv[1])
    fy  = sys.argv[2]
    months = [m.strip() for m in sys.argv[3].split(",")]

    conn = get_connection()
    try:
        for month in months:
            ingest_item_purchases(conn, fp, fy, month)
        conn.commit()
        print("Done.")
    except Exception as e:
        conn.rollback()
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        conn.close()
