"""
Ingest item-level monthly sales from priya_textile.Aggregated Data.

Source: priya_textile."Aggregated Data" table, grouped by ProductID per TimeID.

TimeID mapping for FY 25-26:  52=Apr  53=May  54=Jun  55=Jul  56=Aug  57=Sep
                               58=Oct  59=Nov  60=Dec  61=Jan  62=Feb  63=Mar

Sales realization is preserved as original:
    selling_price_per_kg = SUM(Revenue) / SUM(Quantity)
Purchases are NOT subtracted here — they are handled separately in
ingest_item_purchases (fed into item_purchases_{fy}).

Target table: item_sales_{fy}
    product_id           INT
    month                TEXT
    qty                  REAL   -- total sales qty from Tally invoices
    revenue              REAL   -- total sales revenue
    selling_price_per_kg REAL   -- revenue / qty (original, unadjusted)

Existing rows for the given month are deleted before re-inserting,
so re-running for the same month is safe.
"""

import psycopg2

from .db import get_connection

PRIYA_TEXTILE_DSN = "postgresql://kbg:kbg@localhost:5432/priya_textile"

# TimeID mapping per FY: month_name → TimeID in priya_textile."Aggregated Data"
FY_TIME_ID_MAP: dict[str, dict[str, int]] = {
    "25_26": {
        "Apr": 52, "May": 53, "Jun": 54, "Jul": 55,
        "Aug": 56, "Sep": 57, "Oct": 58, "Nov": 59,
        "Dec": 60, "Jan": 61, "Feb": 62, "Mar": 63,
    },
}


def _create_table(conn, fy: str) -> None:
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS item_sales_{fy} (
            id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id           INTEGER NOT NULL,
            month                TEXT    NOT NULL,
            qty                  REAL,
            revenue              REAL,
            selling_price_per_kg REAL
        )
    """)
    conn.execute(f"""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_item_sales_{fy}_pid_month
        ON item_sales_{fy} (product_id, month)
    """)
    conn.commit()


def ingest_item_sales(conn, fy: str, month: str) -> None:
    """
    Load sales for *month* from priya_textile.Aggregated Data into item_sales_{fy}.

    Groups Quantity and Revenue by ProductID for the configured TimeID.
    Only products with positive total Quantity are included.

    Parameters
    ----------
    conn  : DB connection to priya_financial (returned by get_connection())
    fy    : FY suffix, e.g. '25_26'
    month : Three-letter month abbreviation, e.g. 'Mar'
    """
    time_id_map = FY_TIME_ID_MAP.get(fy)
    if not time_id_map:
        print(f"  ⚠  No TimeID mapping configured for FY {fy} — item_sales ingestion skipped")
        return

    if month not in time_id_map:
        print(f"  ⚠  Month {month!r} not in TimeID map for FY {fy} — skipped")
        return

    time_id = time_id_map[month]

    pt_conn = psycopg2.connect(PRIYA_TEXTILE_DSN)
    try:
        pt_cur = pt_conn.cursor()
        pt_cur.execute(
            """
            SELECT "ProductID", SUM("Quantity") AS qty, SUM("Revenue") AS revenue
            FROM "Aggregated Data"
            WHERE "TimeID" = %s
            GROUP BY "ProductID"
            HAVING SUM("Quantity") > 0
            ORDER BY "ProductID"
            """,
            (time_id,),
        )
        rows = pt_cur.fetchall()
    finally:
        pt_conn.close()

    print(f"  [{month}] Loaded {len(rows)} products from priya_textile TimeID={time_id}")

    _create_table(conn, fy)

    # Filter to manufactured products only — exclude trading goods (PP Sacks, Weed Mat, etc.)
    # Only keep ProductIDs that exist in product_specification.product_code
    allowed_cur = conn.execute(
        "SELECT DISTINCT product_code FROM product_specification WHERE product_code IS NOT NULL"
    )
    allowed_ids = {row[0] for row in allowed_cur.fetchall()}
    before = len(rows)
    rows = [(pid, qty, rev) for pid, qty, rev in rows if int(pid) in allowed_ids]
    print(f"  [{month}] Filtered to {len(rows)} manufactured products "
          f"({before - len(rows)} trading/other excluded)")

    conn.execute(f"DELETE FROM item_sales_{fy} WHERE month = %s", (month,))

    inserted = 0
    for pid, qty, rev in rows:
        qty = float(qty or 0)
        rev = float(rev or 0)
        rate = rev / qty if qty else 0.0
        conn.execute(
            f"""INSERT INTO item_sales_{fy} (product_id, month, qty, revenue, selling_price_per_kg)
                VALUES (%s, %s, %s, %s, %s)""",
            (int(pid), month, qty, rev, rate),
        )
        inserted += 1

    print(f"  [{month}] Inserted {inserted} rows into item_sales_{fy}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 3:
        print("Usage: python -m sheets.ingest_item_sales <fy> <month[,month,...]>")
        print("  e.g. python -m sheets.ingest_item_sales 25_26 Apr,May,Jun")
        sys.exit(1)

    fy = sys.argv[1]
    months_arg = sys.argv[2].split(",")

    conn = get_connection()
    try:
        for m in months_arg:
            ingest_item_sales(conn, fy, m.strip())
        conn.commit()
        print("Done.")
    except Exception as e:
        conn.rollback()
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        conn.close()
